chg: LIFELOG processing changed to FIFO signal processing

diff --git a/include/brasil b/include/brasil
--- a/include/brasil
+++ b/include/brasil
@@ -148,12 +148,12 @@ function _BIL:highlightError {
 ## ------------------------------------------------------------------------------
 ## function: BIL:checkProcessHealth
 ##
-## description: internal function to check if a BRASIL process is still RUNNING
+## description: internal function to check if a BRASIL application is still RUNNING
 ##
 ## usage: BIL:checkProcessHealth <processId>
 ##
 ## returns: 
-##   true:  if <processId> is running
+##   true:  if <processId> is running and producing heartbeats
 ##   false: if <processId> is dead
 ##
 
@@ -161,31 +161,42 @@ function BIL:checkProcessHealth {
   set +x;${BIL_FUNCTION_HEADER}
 
   local pid=${1:-}
+  local currentTimestamp=$(date +%s)
+  local heartbeatTime
+  local timeDiff=0
+  local echoPid
 
-  if [[ ${pid} =~ ^[0-9]+$ ]]; then 
-
-    # if LIFELOG is not already created, simulate life signs
-    if { cat ${BIL_LIFELOG} 2>/dev/null || echo "${pid} $(date +%s)"; } | awk '
-        BEGIN { RC=1 }
-        /^'"${pid}"'/
-        {
-         if (('"$(date +%s)"'-$2) < '"${BIL_LIFELOG_DEATHTIME}"' )
-           RC=0
-         else
-           RC=1
-        }
-        END { exit RC }' >/dev/null 2>&1 
-    then
-      if [ -d /proc/${pid} ]; then
-        true
-      else
-        false
-      fi
-    else
-      false
-    fi
-
+  if [[ "${pid}"x == "${BIL_PROCID}"x && "$$"x == "${BIL_PROCID}"x ]]; then
+    pid=self
   fi
+
+  # Send an request ("ping") to the pid with actual timestamp (non-blocking)
+  { echo "ping-${BIL_PROCID}-$currentTimestamp" > "${BIL_TMPPREFIX}#${pid}_HEARTBEAT" & } 2>/dev/null
+  echoPid=$!
+
+  # send signal SIGUSR2 to the sender
+  kill -SIGUSR2 "$pid"
+
+  sleep 1
+  kill "${echoPid}" &>/dev/null
+
+  echo "checkProcessHealth-${FUNCNAME[1]}[$$]: BIL_HEARTBEAT_TIME=$BIL_HEARTBEAT_TIME"
+
+  heartbeatTime=${BIL_HEARTBEAT_$pid:-$(( currentTimestamp + BIL_HEARTBEAT_DEATHTIME ))}
+  echo "checkProcessHealth-${FUNCNAME[1]}[$$]: heatbeatTime=$heartbeatTime"
+
+  timeDiff=$(( currentTimestamp - heartbeatTime ))
+  echo "checkProcessHealth-${FUNCNAME[1]}[$$]: Timediff=$timeDiff"
+
+  ## No heartbeatTime means death of the process
+  [ -z "${heartbeatTime}" ] && timeDiff=${BIL_HEARTBEAT_DEATHTIME}
+
+  if [[ ${timeDiff} -lt ${BIL_HEARTBEAT_DEATHTIME} ]] && [[ -d /proc/${pid} ]] ; then
+    true
+  else
+    false
+  fi
+
 }
 
 ## ------------------------------------------------------------------------------
@@ -383,30 +394,15 @@ function BIL:die {
 
   ## terminate heartbeat
   ## -------------------
-  BIL:lockFile ${BIL_LIFELOG}
-
-    if [ -n "${BIL_HEARTBEAT_PID}" ]; then
-      if [ -d /proc/${BIL_HEARTBEAT_PID} ]; then
-        kill -9 ${BIL_HEARTBEAT_PID} 2>/dev/null
-        wait ${BIL_HEARTBEAT_PID} 2>/dev/null
-        BIL:msg debug2 "heartbeat-${BIL_APPL_NAME}-${BIL_PROCID} ENDED - PID=${BIL_HEARTBEAT_PID}"
-      else
-        BIL:msg error "heartbeat-${BIL_APPL_NAME}-${BIL_PROCID} ENDED ABNORMALLY - PID=${BIL_HEARTBEAT_PID}"
-      fi
+  if [ -n "${BIL_HEARTBEAT_PID}" ]; then
+    if [ -d /proc/${BIL_HEARTBEAT_PID} ]; then
+      kill -9 ${BIL_HEARTBEAT_PID} 2>/dev/null
+      wait ${BIL_HEARTBEAT_PID} 2>/dev/null
+      BIL:msg debug2 "heartbeat-${BIL_APPL_NAME}-${BIL_PROCID} ENDED - PID=${BIL_HEARTBEAT_PID}"
+    else
+      BIL:msg error "heartbeat-${BIL_APPL_NAME}-${BIL_PROCID} ENDED ABNORMALLY - PID=${BIL_HEARTBEAT_PID}"
     fi
-
-    sed -i "/^${BIL_PROCID}/d" ${BIL_LIFELOG} 2>/dev/null
-
-    lines=$(wc -l ${BIL_LIFELOG} 2>/dev/null|cut -d ' ' -f1)
-    lines=${lines:-0}
-    if [ ${lines} -eq 0 ]; then
-      rm ${BIL_LIFELOG} 2>/dev/null
-
-      # cleanup orphant temp files
-      [ -n "${BIL_TMPPREFIX}" ] && find ${BIL_TMPPREFIX}\#* -delete 2>/dev/null || :
-    fi
-
-  BIL:unlockFile ${BIL_LIFELOG}
+  fi
 
   kill $(jobs -p) 2>/dev/null || :
 
@@ -520,7 +516,6 @@ function BIL:signalHandler {
   local default_action_ok=${BIL_TRUE}
   local user_defined_function
 
-
   BIL_TRAP_SIGNAL=$1
   BIL_TRAP_LINENO=$2
   BIL_TRAP_FUNCTION=$3
@@ -536,8 +531,7 @@ function BIL:signalHandler {
   if [[ "${BIL_EXIT_VIA_DIE}"x != "${BIL_TRUE}"x && ${BIL_TRAP_SIGNAL} != "exit" ]]; then
     if eval [[ ! "\${BIL_SIGNAL_HANDLE_${BIL_TRAP_SIGNAL}}" = "${BIL_FALSE}" ]]; then
       BIL:msg debug2 "TRAP SIGNAL \"${BIL_TRAP_SIGNAL}\" RECEIVED - FUNCTION: ${BIL_TRAP_FUNCTION[@]}, SOURCE: ${BIL_TRAP_SOURCE}, LINE: ${BIL_TRAP_LINENO}"
-      BIL:msg debug "TRAP \"${BIL_TRAP_SIGNAL}\" CAUGHT"
-      [ "${BIL_INCLUDE_SCRIPT_RUNNING}"x != ""x ] && BIL:msg debug "Trap occured inside of the include script \"${BIL_INCLUDE_SCRIPT_RUNNING}\""
+      [ "${BIL_INCLUDE_SCRIPT_RUNNING}"x != ""x ] && BIL:msg debug "TRAP OCCURED INSIDE of the INCLUDE SCRIPT \"${BIL_INCLUDE_SCRIPT_RUNNING}\""
     else
       BIL:msg debug2 "TRAP SIGNAL \"${BIL_TRAP_SIGNAL}\" RECEIVED - FUNCTION: ${BIL_TRAP_FUNCTION[@]}, SOURCE: ${BIL_TRAP_SOURCE}, LINE: ${BIL_TRAP_LINENO}"
       BIL:msg debug "TRAP SIGNAL \"${BIL_TRAP_SIGNAL}\" CAUGHT BUT IGNORED"
@@ -569,7 +563,7 @@ function BIL:signalHandler {
 
   if [ ${default_action_ok} -eq ${BIL_TRUE} ]; then
     case ${BIL_TRAP_SIGNAL} in
-      1| "SIGHUP")          BIL_SIGNAL_HANDLER_RUNNING=${BIL_FALSE}
+      1| "SIGHUP")          BIL_SIGNAL_SIGNAL_HANDLER_RUNNING=${BIL_FALSE}
                             BIL:unlockTrap
                             ;;
       2|"SIGINT")           if [ ${BIL_USER_BREAK_ALLOWED} -eq ${BIL_TRUE} ]; then
@@ -582,7 +576,10 @@ function BIL:signalHandler {
       15|"SIGTERM")         BIL:die 251 "SCRIPT ABORTED by the external SIGNAL TERM";;
       "SIGUSR1")            :
                             ;;
-      "SIGUSR2")            :
+      "SIGUSR2")            BIL_SIGNAL_HANDLER_RUNNING=${BIL_FALSE}
+                            BIL:unlockTrap
+                            
+                            :
                             ;;
       "SIGERR")             set +o errexit
                             BIL:msg error "A COMMAND ENDED WITH an ERROR - RC=${rc}"
@@ -681,7 +678,7 @@ function BIL:createTemp {
 
     set -o nounset
 
-    BIL:msg debug2 "CREATED \"$name\" TEMPORARY $(x=${mode#--}; echo ${x^^})"
+    BIL:msg debug2 "CREATED \"$name\" TEMPORARY $(x=${mode#--}; echo ${x^^}) - DSN=${tempfile}"
 
   else
     BIL:msg err "CREATING \"$name\" TEMPORARY $(x=${mode#--}; echo ${x^^}) FAILED"
@@ -804,8 +801,8 @@ function BIL:lockFile {
           break
         fi
 
-        ## if lockfile is blocked for non existant procid delete the lockfile
-        ## ------------------------------------------------------------------
+        ## if lockfile is blocked from a non responding process, then delete the lockfile
+        ## ------------------------------------------------------------------------------
         if [[ "${pid}" =~ ^[0-9]+$ ]]; then
           BIL:checkProcessHealth ${pid} || { rm -f ${lockfile} >/dev/null 2>&1; } || : # remove without raising an error
         else
@@ -871,8 +868,8 @@ function BIL:unlockFile {
   if [ -s ${lockfile} ]; then
     pid=$(head -1 $lockfile 2>/dev/null)
 
-    ## if lockfile is blocked for non existant procid delete the lockfile
-    ## ------------------------------------------------------------------
+    ## if lockfile is blocked by an unresponsive process, thean delete the lockfile
+    ## ----------------------------------------------------------------------------
     if [[ "${pid}" =~ ^[0-9]+$ ]]; then
       BIL:checkProcessHealth ${pid} || { rm -f ${lockfile} 2>/dev/null || : ;} # remove without raising an error
 
@@ -1642,7 +1639,8 @@ function BIL:execFunction {
 
   local newName
   local funcName
-  local parms
+  local parms=""
+
   case $# in
   0) BIL:die 8 "BIL:execFunction: EXPECTED PARAMETERS \"<newName> <funcName>\" NOT PASSED!"
      ;;
@@ -1669,7 +1667,12 @@ function BIL:execFunction {
 ## ------------------------------------------------------------------------------
 ## function: BIL:heartbeat
 ##
-## description: regularly write the actual time to the ${BIL_LIFELOG} logfile
+## description: This SIGUSR2 function processes the BIL_HEARTBEAT_FIFO
+##              There are two types of messages in this fifo:
+##                ping-<spid>-<timestamp> and pong-<rpid>-<timestamp>.
+##              Ping messages are coming from source pids (spid) to ask for life signs.
+##              A pong-${BIL_PROCID}-<timestamp> message is send to the spid.
+##              Pong messages are responses from rewuested systems to their vital signs. 
 ##
 ## usage: BIL:heartbeat
 ##
@@ -1677,54 +1680,97 @@ function BIL:execFunction {
 function BIL:heartbeat {
   set +x;${BIL_FUNCTION_HEADER}
 
-  BIL:lockFile ${BIL_LIFELOG}
+  local line
+  local senderPid
+  local senderTimestamp
+  local receiverPid
+  local receiverTimestamp
+  local currentTimestamp=$(date +%s)
+  local echoPid
 
-    grep -q "^${BIL_PROCID}" ${BIL_LIFELOG} 2>/dev/null || echo "${BIL_PROCID} $(date +%s)" >> ${BIL_LIFELOG}
+  # Read every line of the FIFO an process it
+  while read -r line; do
+    # check whether it is a ping or pong message
+    if [[ $line == ping-* ]]; then
+      # Extracting sender pid and timestamp from message
+      senderPid=${line#ping-}
+      senderPid=${sender_pid%-*}
+      senderTimestamp=${line##*-}
 
-  BIL:unlockFile ${BIL_LIFELOG}
+      if [ -p "${BIL_TMPPREFIX}#${senderPid}_HEARTBEAT" ]; then
+        # Send an answer ("pong") to the sender with actual timestamp (non-blocking)
+        { echo "pong-${BIL_PROCID}-$currentTimestamp" > "${BIL_TMPPREFIX}#${senderPid}_HEARTBEAT" & } 2>/dev/null
+        echoPid=$!
+
+        # send signal SIGUSR2 to the sender
+        kill -SIGUSR2 "$senderPid" 
+
+        sleep 1
+        kill "${echoPid}" &>/dev/null
+      fi
+
+    fi
+    elif [[ $line == pong-* ]]; then
+      # Extracting receiver pid and timestamp from message
+      receiverPid=${line#pong-}
+      receiverPid=${receiver_pid%-*}
+      receiverTimestamp=${line##*-}
+
+      # export variable to save the timestamp of the requested process 
+      eval "export BIL_HEARTBEAT_$receiverPid=$receiverTimestamp"
+    fi
+
+  done < <(cat <> "${BIL_HEARTBEAT_FIFO}" < "${BIL_HEARTBEAT_FIFO}")
+
+}
+
+## ------------------------------------------------------------------------------
+## function: BIL:monitorHeartbeat
+##
+## description: Periodicaly send signal SIGUSR2 to parent process to update BIL_HEARTBEAT_${BIL_PROCID} env variable.
+##              Terminate the father process (BIL_PROCID) cleanly if the time difference between the current time 
+##              and the BIL_HEARTBEAT_TIME variable is greater than BIL_HEARTBEAT_DEATHTIME.
+##
+## usage: BIL:monitorHeartbeat
+##
+
+function BIL:monitorHeartbeat {
+  set +x;${BIL_FUNCTION_HEADER}
+
+  local pidApp
+  local pidTimeout
 
   while true; do
 
     if [ ! -d /proc/${BIL_PROCID} ]; then
-      ( BIL:die 8 "${BIL_APPL_NAME} ENDED ABNORMALY - CLEANING UP NOW..."; sleep ${BIL_LIFELOG_DEATHTIME} ) &
-      wait $!
+      BIL:die 8 "${BIL_APPL_NAME} ENDED ABNORMALY - CLEANING UP NOW!" &
+      pidApp=$!
+ 
+      (sleep 60) &
+      pidTimeout=$!
+
+      wait ${pidApp}
+      (kill -0 $pidTimeout && kill $pidTimeout 2>/dev/null) || true
       break
     fi
 
-    if BIL_APPL_LOCK_MAXWAIT=${BIL_LIFELOG_DEATHTIME} BIL:lockFile ${BIL_LIFELOG}; then
+    if ! BIL:checkProcessHealth ${BIL_PROCID}; then
+      BIL:msg error "TIMEOUT during HEARTBEAT MONITORING (${BIL_HEARTBEAT_DEATHTIME}s) - TERMINATING \"${BIL_PROCID}\" process GENTLY NOW!"
+      BIL:msg error "CURRENTLY $(_BIL:cpuLoad)% CPU LOAD"
+      kill -15 ${BIL_PROCID} 2>/dev/null
 
-      if grep -q "^${BIL_PROCID}" ${BIL_LIFELOG} 2>/dev/null; then
-          sed -i 's/^'"${BIL_PROCID}"' .*/'"${BIL_PROCID} $(date +%s)"'/' ${BIL_LIFELOG} 2>/dev/null
-      else
-        break
-      fi
+      sleep $(( ${BIL_HEARTBEAT_INTERVAL} * 6 ))
 
-      BIL:unlockFile ${BIL_LIFELOG}
-    else
       if [ -d /proc/${BIL_PROCID} ]; then
-        BIL:msg error "HEARTBEAT TIMEOUT (${BIL_LIFELOG_DEATHTIME}s) ACQUIRING LIFELOG - TERMINATING \"${BIL_PROCID}\" PROCESS GENTLY NOW!"
-        BIL:msg error "ACTUAL $(_BIL:cpuLoad)% CPU LOAD"
-        kill -15 ${BIL_PROCID} 2>/dev/null
-
-        ( sleep ${BIL_LIFELOG_DEATHTIME}
-
-          if [ -d /proc/${BIL_PROCID} ]; then
-            BIL:msg error "PROCESS CLEAN EXIT of \"${BIL_PROCID}\" FAILED - KILLING UNCONDITIONALY NOW!"
-            kill -9 ${BIL_PROCID} 2>/dev/null
-          fi
-        )&
-
+        BIL:msg error "CLEAN PROCESS TERMINATION of \"${BIL_PROCID}\" FAILED - KILLING UNCONDITIONALY NOW!"
+        kill -9 ${BIL_PROCID} 2>/dev/null
       fi
-
       break
     fi
 
-    ( sleep ${BIL_LIFELOG_INTERVAL} ) &
-    wait $!
+    sleep ${BIL_HEARTBEAT_INTERVAL}
 
   done
-
-  BIL:unlockFile ${BIL_LIFELOG}
 
   exit 0
 }
@@ -1764,16 +1810,18 @@ function BIL:init {
     BIL:include ${BIL_APPL_CONFIG}
   fi
 
+
   [ -z "${BIL_APPL_NAME}" ] && BIL_APPL_NAME="${BIL_APPL_CMD}"
+
+  case ${BIL_SUPPORTED_OS} in
+    *"$BIL_OS "*|*" $BIL_OS") :;;
+    *) BIL:die 8 "OPERATING SYSTEM \"$(uname -s)\" IS NOT SUPPORTED!";;
+  esac
 
   [[ -n "${BIL_LOGFILE}"  && ! -a "${BIL_LOGFILE}"  ]] && :> ${BIL_LOGFILE}
   [[ -n "${BIL_ULOGFILE}" && ! -a "${BIL_ULOGFILE}" ]] && :> ${BIL_ULOGFILE}
 
   BIL:parseParms "$@"
-
-  ( BIL:execFunction heartbeat-${BIL_APPL_NAME}-${BIL_PROCID} BIL:heartbeat ) &
-  BIL_HEARTBEAT_PID=$!
-
 
   if [ -s "${BIL_APPL_CONFIG}" ]; then
     BIL:msg debug "USING \"${BIL_APPL_CONFIG}\" APPL CONFIG"
@@ -1816,24 +1864,24 @@ function BIL:init {
       BIL:createTemp --file TMPFILE${i} && eval BIL_TMPFILE${i}="${BIL_TMPPREFIX}#${BIL_PROCID}_TMPFILE${i}"
   done
 
+  ## create Heartbeat process
+  ## ------------------------
+  BIL:createTemp --fifo HEARTBEAT && BIL_HEARTBEAT_FIFO="${BIL_TMPPREFIX}#${BIL_PROCID}_HEARTBEAT"
+  ( BIL:execFunction heartbeat-${BIL_APPL_NAME}-${BIL_PROCID} BIL:monitorHeartbeat ) &
+  BIL_HEARTBEAT_PID=$!
+
   BIL:msg debug2 "heartbeat-${BIL_APPL_NAME}-${BIL_PROCID} STARTED - PID=${BIL_HEARTBEAT_PID}"
 
   if [ -s "${BIL_DEFAULT_CONFIG}" ]; then
     BIL:msg debug "USING \"${BIL_DEFAULT_CONFIG}\" DEFAULT CONFIG"
   fi
 
-  BIL:msg info "WAITING for \"${BIL_APPL_NAME}\" QUEUE - MODE=${BIL_RUNTYPE^^}${BIL_PARALLEL:+; COUNT=$BIL_PARALLEL}"
-
-  if BIL:waitforQueue --${BIL_RUNTYPE,,} ${BIL_APPL_NAME}; then
-
-    BIL:msg info "OBTAINING \"${BIL_APPL_NAME}\" ${BIL_RUNTYPE^^} QUEUE SUCCESSFULL"
-  else
-    BIL:die 8 "OBTAINING \"${BIL_APPL_NAME}\" ${BIL_RUNTYPE^^} QUEUE FAILED!"
-  fi
-
   BIL:msg debug "BRASIL v${BIL_VERSION} INITIALIZED" && BIL_INITIALIZED="${BIL_TRUE}"
 
   BIL:unlockTrap
+
+
+
 
 }
 
@@ -1857,12 +1905,21 @@ function BIL:run {
   while [ $(($(echo ${cpu}|cut -d"." -f1)*100+$(( 10#$(echo ${cpu}|cut -d"." -f2) )) )) -gt $((${BIL_MAX_CPU_PCT}*100)) ]; do
     # sleep randomly between 5 and 10.99 seconds to take cpu load into consideration
     sleepTime=$(_BIL:random 5 10).$(_BIL:random 1 99)
-    BIL:msg debug2 "${cpu}% CPU LOAD - SLEEPING ${sleepTime}s"
+    BIL:msg debug2 "CURRENTLY ${cpu}% CPU LOAD - SLEEPING ${sleepTime}s"
     sleep ${sleepTime}
     cpu=$(_BIL:cpuLoad)
   done
 
-  BIL:msg notice "${BIL_APPL_CMD} ${BIL_APPL_VERSION:+v${BIL_APPL_VERSION}} STARTED - HOSTNAME=${BIL_HOST}, OS=${BIL_OS}, APPLID=${BIL_APPL_ID}, CPU=${cpu}%"
+  BIL:msg info "WAITING for \"${BIL_APPL_NAME}\" QUEUE - MODE=${BIL_RUNTYPE^^}${BIL_PARALLEL:+; COUNT=$BIL_PARALLEL}"
+
+  if BIL:waitforQueue --${BIL_RUNTYPE,,} ${BIL_APPL_NAME}; then
+
+    BIL:msg info "OBTAINING \"${BIL_APPL_NAME}\" ${BIL_RUNTYPE^^} QUEUE SUCCESSFULL"
+  else
+    BIL:die 8 "OBTAINING \"${BIL_APPL_NAME}\" ${BIL_RUNTYPE^^} QUEUE FAILED!"
+  fi
+
+  BIL:msg notice "${BIL_APPL_CMD} ${BIL_APPL_VERSION:+v${BIL_APPL_VERSION}} STARTED - HOSTNAME=${BIL_HOST}, OS=${BIL_OS}, ARCH=${BIL_MACHINE_ARC}, APPLID=${BIL_APPL_ID}, CPU=${cpu}%"
 
   if [ -n "${BIL_TIME}" ];then
     BIL:msg notice "SETTING ${BIL_TIME}s MAXIMUM EXECUTION TIME"
@@ -2023,7 +2080,7 @@ BIL:done
   BIL_SIGNAL_HANDLE_SIGEXIT=${BIL_SIGNAL_HANDLE_SIGEXIT:-${BIL_TRUE}}
   BIL_SIGNAL_HANDLE_SIGTERM=${BIL_SIGNAL_HANDLE_SIGTERM:-${BIL_TRUE}}
   BIL_SIGNAL_HANDLE_SIGUSR1=${BIL_SIGNAL_HANDLE_SIGUSR1:-${BIL_FALSE}}
-  BIL_SIGNAL_HANDLE_SIGUSR2=${BIL_SIGNAL_HANDLE_SIGUSR2:-${BIL_FALSE}}
+  BIL_SIGNAL_HANDLE_SIGUSR2=${BIL_SIGNAL_HANDLE_SIGUSR2:-${BIL_TRUE}}
   BIL_SIGNAL_HANDLE_SIGALRM=${BIL_SIGNAL_HANDLE_SIGALRM:-${BIL_TRUE}}
   BIL_SIGNAL_HANDLE_SIGERR=${BIL_SIGNAL_HANDLE_SIGERR:-${BIL_FALSE}}
   BIL_SIGNAL_SIGHUP_FUNCTION=""
@@ -2032,7 +2089,7 @@ BIL:done
   BIL_SIGNAL_SIGEXIT_FUNCTION=""
   BIL_SIGNAL_SIGTERM_FUNCTION=""
   BIL_SIGNAL_SIGUSR1_FUNCTION=""
-  BIL_SIGNAL_SIGUSR2_FUNCTION=""
+  BIL_SIGNAL_SIGUSR2_FUNCTION="BIL:heartbeat"
   BIL_SIGNAL_SIGALRM_FUNCTION=""
   BIL_SIGNAL_SIGERR_FUNCTION=""
   BIL_RUNTYPE=${BIL_RUNTYPE:-PARALLEL}
@@ -2040,9 +2097,8 @@ BIL:done
   BIL_TMPPREFIX=${BIL_TMPDIR}/BIL_${BIL_APPL_ID}_
   BIL_VERSION_COLOR="LBLUE+BOLD"
   BIL_MSG_BUFFER="${BIL_TMPPREFIX}#${BIL_PROCID}_MSG_BUFFER"
-  BIL_LIFELOG="${BIL_TMPPREFIX}LIFELOG"
-  BIL_LIFELOG_INTERVAL=5
-  BIL_LIFELOG_DEATHTIME=300
+  BIL_HEARTBEAT_INTERVAL=5
+  BIL_HEARTBEAT_DEATHTIME=300
   BIL_DEBUG=${BIL_DEBUG:-1}
   LD_LIBRARY_PATH=${LD_LIBRARY_PATH:-}
   BIL_BASE_HELP_OPTIONS="
@@ -2096,14 +2152,23 @@ $(echo -e $BIL_COL_BOLD)OPTIONS:$(echo -e $BIL_COL_RESET)
   BIL_DEFAULT_CONFIG=${BIL_DEFAULT_CONFIG:-$(grep -lR --include "${BIL_APPL_CORE_CMD%.*}.cfg" --include "${BIL_APPL_CORE_CMD%.*}.conf" --include "${BIL_APPL_CORE_CMD%.*}.config" --exclude "${BIL_APPL_CORE_CMD}" '.*' $(cd ${BIL_BASE_BINDIR}/..; pwd) 2>/dev/null|head -1)}
   BIL_USERNAME=${BIL_USERNAME:-$(id -nu)}                                               # real user name
   BIL_GROUPNAME=${BIL_GROUPNAME:-$(id -ng)}                                             # real group name
+  BIL_HEARTBEAT_TIME=$(date +%s)
   #BIL_STTY_SETTINGS="$( stty -g 2>/dev/null)"                                          # saved STTY settings
   BIL_ORIGINAL_UMASK="$( umask )"
   BIL_ORIGINAL_DIR=$(pwd)
   BIL_HOST="$(uname -n|cut -f1 -d'.')"
-  BIL_OS="$(uname -s)"
+  case "$(uname -s)" in
+    Linux*)  BIL_OS=linux;;
+    AIX*)    BIL_OS=aix;;
+    HP-UX*)  BIL_OS=hpux;;
+    SunOS*)  BIL_OS=sunos;;
+    Darwin*) BIL_OS=darwin;;
+    *)       BIL_OS=unknown;;
+  esac
+  BIL_SUPPORTED_OS="linux " 								# List of supported operating systems seperated by spaces
   BIL_OS_VERSION="$(uname -r)"
   BIL_OS_RELEASE="$(uname -v)"
-  BIL_MACHINE_ARC="$(uname -p)"
+  BIL_MACHINE_ARC="$(uname -m)"
   BIL_START_TIMER=$(date "+%s.%N")
   BIL_ULOGCMD='cat - >> ${BIL_ULOGFILE}'
   BIL_LOGCMD='cat - >> ${BIL_LOGFILE}'
